name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore WinFormsApp1\WinFormsApp1.csproj

    - name: Clean
      run: dotnet clean WinFormsApp1\WinFormsApp1.csproj --configuration Release

    - name: Build
      run: dotnet build WinFormsApp1\WinFormsApp1.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish WinFormsApp1\WinFormsApp1.csproj --configuration Release --self-contained --runtime win-x64 --output ${{ runner.temp }}/publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: OOPDemo
        path: ${{ runner.temp }}/publish
